name: "Publish Release"

on:
  push:
    branches:
      - tags # 当推送到 main 分支时触发，你也可以改为 tags

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-22.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      # 1. 设置 Node.js 环境
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 2. 设置 Rust 环境
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      # 3. 安装 Linux 依赖 (仅在 Ubuntu 上运行)
      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev patchelf

      # 4. 安装前端依赖
      - name: install frontend dependencies
        run: npm install # 如果你用 yarn 或 pnpm，请更换对应命令

      # 5. 使用 Tauri 官方 Action 进行构建并创建 GitHub Release
      - name: build and release
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__ # 自动从 tauri.conf.json 读取版本号
          releaseName: "Paste App v__VERSION__"
          releaseBody: "See the assets below to download the latest version."
          releaseDraft: true
          prerelease: false